### ISSUE TITLE
ffi.error: symbol 'cairo_image_surface_create' not found in library 'C:\Programming\GTK3\bin\libcairo-gobject-2.dll': error 0x7f

### ISSUE THREAD

**Issue by apacha** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#18]
I've used the binaries from here to get a [Keras example](https://github.com/keras-team/keras/blob/master/examples/image_ocr.py) up and running on one machine. Interestingly I tried reproduce it on another machine, but all of a sudden I am getting the following error:

```
Traceback (most recent call last):
  File "image_ocr.py", line 503, in <module>
    train(run_name, 0, 20, 128)
  File "image_ocr.py", line 498, in train
    initial_epoch=start_epoch)
  File "C:\Programming\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Programming\Anaconda3\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "C:\Programming\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "C:\Programming\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Programming\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "image_ocr.py", line 295, in next_train
    ret = self.get_batch(self.cur_train_index, self.minibatch_size, train=True)
  File "image_ocr.py", line 279, in get_batch
    X_data[i, 0:self.img_w, :, 0] = self.paint_func(self.X_text[index + i])[0, :, :].T
  File "image_ocr.py", line 314, in <lambda>
    rotate=False, ud=False, multi_fonts=False)
  File "image_ocr.py", line 85, in paint_text
    surface = cairo.ImageSurface(cairo.FORMAT_RGB24, w, h)
  File "C:\Programming\Anaconda3\lib\site-packages\cairocffi\surfaces.py", line 643, in __init__
    pointer = cairo.cairo_image_surface_create(format, width, height)
ffi.error: symbol 'cairo_image_surface_create' not found in library 'C:\Programming\GTK3\bin\libcairo-gobject-2.dll': error 0x7f
```

On the other machine I first followed the instructions from https://www.gtk.org/download/windows.php, but since it didn't work, I used the exe from this Repo and got it up and running. Replicating that in any order did not work. :-(

Any idea on why this might happen?

**Comment by tschoonj** [comment]
Hi @apacha 

You are mixing two cairo dlls: the ones provided by the Gtk runtime installer and those provided by anaconda. I am guessing that in this case the Gtk runtime installer dlls location has priority on the path so it gets used but is apparently lacking a symbol that is present in its anaconda counterpart.

You should not have to install the Gtk runtime to get this working: uninstall it. Afterwards anaconda python should pick up the cairo dlls provided by anaconda.

Hope this helps!

Tom

**Comment by apacha** [comment]
You are right. Removing the GTK+ toolkit and installing cairo via `conda install cairo` did the trick! Many thanks!

**Comment by tschoonj** [comment]
Glad to hear that you it working. 

As a general rule, you should never have anything within an anaconda installation depend on something outside of it, especially if it concerns dlls.
